#JPA
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/a505?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: a505
    password: a505
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        default_batch_fetch_size: 100

#oauth2
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 10465e80bd5ace45891af917d7781def
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

#이미지
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#카카오 어드민키
kakao:
  admin : 4834af6c4c44729312c5b43d38dd3516
  redirect : http://localhost:8081

#jwt
jwt:
  secret: zoqxlsthwjdWkdWkdaos


#s3
cloud:
  aws:
    credentials:
      access-key: AKIA4GUKC3ODS4UKFMWD
      secret-key: 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
    s3:
      bucket: sarac-a505
    region:
      static: ap-northeast-2 # 리전 정보
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

#알라딘
aladin:
  ttbkey: ttbdanijde711853001


